### ISSUE TITLE
Install app using rnpm

### ISSUE THREAD

**Issue by charlires** [charlires/react-native-segment-analytics#1]

**Comment by afilp** [comment]
@charlires Did you have any progress with this? It seems that we have to do lots of stuff in order to install the CocoaPods! See here: http://stackoverflow.com/questions/20755044/how-to-install-cocoa-pods

**Comment by af7** [comment]
@charlires I use the pod 'Analytics' command and it says "Unknown command", maybe I should enter something else?

**Comment by afilp** [comment]
@charlires 
The instructions say:

"Make sure that you have libAnalytics.a and libSegmentAnalytics.a in your Linked Frameworks and Libraries You may have to import them manually."

Where do I find these 2 files? I searched everywhere and could not find them to link them.

**Comment by afilp** [comment]
All I get after ipod install is this:

"libPods-myApp.a in Frameworks */,

But this then fails in the compilation

**Comment by idris** [comment]
Pull Request submitted: #12
