### ISSUE TITLE
Passing in empty map for traits/properties results in NPE

### ISSUE THREAD

**Issue by jlo1** [charlires/react-native-segment-analytics#13]
`toMap` shouldn't allow `readableMap` to be nullable here: https://github.com/charlires/react-native-segment-analytics/blob/028875b8ade22406f928fff2322014dfda65159a/android/src/main/java/com/charlires/segmentanalytics/SegmentAnalyticsModule.java#L106

Should short-circuit and return from `toTraits` and `toProperties` early if `(= readableMap null)` OR `(empty? readableMap)`

**Comment by charlires** [comment]
@jlo1 Should be fixed by your pull request, Thank you!
