### ISSUE TITLE
Incorrect import for MainApplication.java in readme

### ISSUE THREAD

**Issue by ksarna** [charlires/react-native-segment-analytics#3]
Import in MainApplication.java should be equal to:
`import com.charlires.segmentanalytics.SegmentAnalyticsPackage;`
instead of mentioned `import com.charlires.segmentanalytics;`

PS Great job, thank you for doing this.

**Comment by afilp** [comment]
@ksarna I agree, thank you for writing this as I was a little stuck. Would you care to create a PR for this? Or I can do it if you don't have time.

**Comment by charlires** [comment]
Thank you both for your interest, is fixed now
