### ISSUE TITLE
RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by adamclark64** [charlires/react-native-segment-analytics#4]
Getting this isssue in xcode when I try to build on first installation:

```
Lexical or Preprocessor Issue Group

'RCTBridgeModule.h' file not found

In file included from /Users/{usr}/repos/repo/node_modules/react-native-segment-analytics/ios/SegmentAnalytics/Classes/SegmentAnalytics.m:5:
```

**Comment by adamclark64** [comment]
I fixed this by starting over.  Cant confirm if this was merely user error

**Comment by grydstedt** [comment]
This happening often, but then will magically disappear after a while. Any idea what is going with this?

**Comment by KabirKang-zz** [comment]
I have been getting this recently and can't build my project on iOS

**Comment by roycclu** [comment]
Add this line to the SegmentAnalytics.podspec file

```
  s.dependency 'React'
```

Should fix it
